// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmaIWSA9QzYFJxSKFmBGC_pOK-Ac-6Xfs',
    appId: '1:1058488227735:web:cfbe06b8972d527a4ad6d2',
    messagingSenderId: '1058488227735',
    projectId: 'flowerly-app',
    authDomain: 'flowerly-app.firebaseapp.com',
    storageBucket: 'flowerly-app.firebasestorage.app',
    measurementId: 'G-KS4J2RPGPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYlZvJQI1LBqTnzCT-6Zv9p6rk5e2vTIc',
    appId: '1:1058488227735:android:9d9ab8cf55a5068e4ad6d2',
    messagingSenderId: '1058488227735',
    projectId: 'flowerly-app',
    storageBucket: 'flowerly-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKBpbl2LM-yvYRUsEWkt3O6-s_UKkT460',
    appId: '1:1058488227735:ios:148d42c8286531324ad6d2',
    messagingSenderId: '1058488227735',
    projectId: 'flowerly-app',
    storageBucket: 'flowerly-app.firebasestorage.app',
    iosBundleId: 'com.example.flowerlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKBpbl2LM-yvYRUsEWkt3O6-s_UKkT460',
    appId: '1:1058488227735:ios:148d42c8286531324ad6d2',
    messagingSenderId: '1058488227735',
    projectId: 'flowerly-app',
    storageBucket: 'flowerly-app.firebasestorage.app',
    iosBundleId: 'com.example.flowerlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmaIWSA9QzYFJxSKFmBGC_pOK-Ac-6Xfs',
    appId: '1:1058488227735:web:109f48e97f64e22d4ad6d2',
    messagingSenderId: '1058488227735',
    projectId: 'flowerly-app',
    authDomain: 'flowerly-app.firebaseapp.com',
    storageBucket: 'flowerly-app.firebasestorage.app',
    measurementId: 'G-VM7XZY7CYD',
  );

}