// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh_TKXDv_M3xb_oPBD1JCWwfccw8a9nZ8',
    appId: '1:361944692662:web:07d920ba0f46a1362d7317',
    messagingSenderId: '361944692662',
    projectId: 'flowershop-c3cd7',
    authDomain: 'flowershop-c3cd7.firebaseapp.com',
    storageBucket: 'flowershop-c3cd7.firebasestorage.app',
    measurementId: 'G-SGT3M1ZD9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI5rMUwfIEjDKV9c15ZAqkWRNWJa3egoM',
    appId: '1:361944692662:android:6692a15f4c4b36c42d7317',
    messagingSenderId: '361944692662',
    projectId: 'flowershop-c3cd7',
    storageBucket: 'flowershop-c3cd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Q3ucAz2X0eS--0Iv2mbSgqmRPmU2frs',
    appId: '1:361944692662:ios:fd50ed5d61d588562d7317',
    messagingSenderId: '361944692662',
    projectId: 'flowershop-c3cd7',
    storageBucket: 'flowershop-c3cd7.firebasestorage.app',
    iosBundleId: 'com.example.flowerShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Q3ucAz2X0eS--0Iv2mbSgqmRPmU2frs',
    appId: '1:361944692662:ios:fd50ed5d61d588562d7317',
    messagingSenderId: '361944692662',
    projectId: 'flowershop-c3cd7',
    storageBucket: 'flowershop-c3cd7.firebasestorage.app',
    iosBundleId: 'com.example.flowerShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh_TKXDv_M3xb_oPBD1JCWwfccw8a9nZ8',
    appId: '1:361944692662:web:31f589331b1cb7282d7317',
    messagingSenderId: '361944692662',
    projectId: 'flowershop-c3cd7',
    authDomain: 'flowershop-c3cd7.firebaseapp.com',
    storageBucket: 'flowershop-c3cd7.firebasestorage.app',
    measurementId: 'G-PNQCLJVXHV',
  );
}
